### ISSUE TITLE
Options for colours and identity masking

### ISSUE THREAD

**Issue by schultzm** [arvestad/alv#11]
Hi arvestad, 

Thanks again for this program.  Feature requests: 1) Allow user to change base colours (it's difficult to see black text on a dark blue background)
<img width="456" alt="Screen Shot 2020-03-19 at 08 42 08" src="https://user-images.githubusercontent.com/5474971/77010260-8d628180-69bd-11ea-8a8e-54f6b9d3cc40.png">
; 2) allow user to set first sequence as reference so that other seqs can be viewed with masked bases, so the above alignment would only have `.` for each base in all but the first sequence.  Or like this: 

```
AAATTTGGCTA
T....CAATAG
```

All the best,

**Comment by arvestad** [comment]
Thanks for the suggestion. I will take a look at this. The color choice is not optimally implemented, so might take too much work for me at this point. I started to restructure the coloring code last year but that was too much of an effort at the time unfortunately.

**Comment by arvestad** [comment]
Hi @schultzm !
I implemented a new option for alignment output: -d or --dotted. I think this addresses your feature request #2.

I did not work on user control for colors, but switched blue for cyan in the output. In my terminals the blue was pretty good, but so is cyan. Hopefully that helps you. 

I have made v1.5 available on PyPI, so just `pip install --upgrade alv`. It would be good with some quick feedback on the implementation, if you can help me with that. 

Best,
Lars

**Comment by camilogarciabotero** [comment]
Hi @arvestad 

I was following this issue since the color issue had happened to me as well. The upgrade was very cool and enhanced the visualization of DNA sequences. However, when watching protein sequences. The dark blue is still there for some AA and the cyan is already taken by some others. Not sure if this was an expected output.

![Screen Shot 2020-03-19 at 10 25 31 AM](https://user-images.githubusercontent.com/25586362/77083740-f8b35000-69cb-11ea-81b4-7911b9807a8c.png)

Regarding the `--dotted` option. It seems that the first codon doesn't display a white background and then the dots are unperceived in the first column, and other thing I could spot is that the bases are dark blue under this option:

![Screen Shot 2020-03-19 at 10 33 26 AM](https://user-images.githubusercontent.com/25586362/77084526-1208cc00-69cd-11ea-8e10-195ba5181a3e.png)

Cheers,
Camilo.

**Comment by schultzm** [comment]
Hi @arvestad ,

Thanks for addressing these requests so quickly.  We are using your software to visualise primer alignments for COVID19.  I have installed the update.  A lot of improvements are there.  It seems that the white color on the dots doesn't spill over into the bottom sequences and doesn't  propagate past an IUPAC code and the nice DNA colors don't happen when the sequence type is auto-detected (probably due to IUPAC codes in my sequences) (see screenshots).  
<img width="1025" alt="Screen Shot 2020-03-20 at 10 58 15" src="https://user-images.githubusercontent.com/5474971/77125496-059e7500-6a9a-11ea-984e-a6b00477e561.png">


The nice colors do happen when I use the `-t dna` option:

<img width="1114" alt="Screen Shot 2020-03-20 at 11 08 42" src="https://user-images.githubusercontent.com/5474971/77125850-45199100-6a9b-11ea-981b-7efd494aa973.png">

**Comment by arvestad** [comment]
Hi,

I only changed colors for DNA, because the color usage is a bit different with the 20 amino acids, so that was expected. Not sure how work it. Have you tried the Taylor color scheme, for example? I don’t mind adding another (preferably standard) color scheme if you have one for amino acids.

Codon alignments are view using the amino acid color schemes, so no change was intended there. The other effects (black starting background etc) are however unintended effects (i.e., bugs). Will try to take care of that this weekend.	

Thanks a lot!
L

**Comment by arvestad** [comment]
Yes, so the white starting background is a bug, but the unchanged color when auto detecting sequence type is not a bug but a feature, sorry, and I am not inclined to change that. You found the workaround that I think makes most sense. I am however happy to add another color scheme for amino acids though, if you have one to suggest. Do note that you can try ”-c taylor” now, if that would help?

Thanks for reporting the background bug. Hope to fix that this weekend.

	best,
	Lars

**Comment by arvestad** [comment]
Hi @schultzm  and @camilogarciabotero ,
I think the colouring bug is fixed now. Have a look (`pip install --upgrade alv`) and please let me know how it goes.

Lars
