### ISSUE TITLE
alv: 'charmap' codec can't encode character '\u2191'

### ISSUE THREAD

**Issue by karinlag** [arvestad/alv#4]
I am testing this one, and first, I want to say, what a nice little tool!

I am having a small issue though: no matter what input I use I get the following error:

alv: 'charmap' codec can't encode character '\u2191' in position 6: character maps to <undefined>

Note, the position is different from file to file. I am using conda, with Python 3.6.4, with alv installed in its own environment.

Note: there may very well be something wrong with my install and not your program, but I thought I'd bring it up just in case.

**Comment by arvestad** [comment]
Thanks!

I wrote a paragraph of response, blaming unicode etc, when I decided to google search the character you get a problem with. And it turns out to be the up-arrow that I use under the alignment blocks to indicate the columns coordinates refer to. I guess I should revert back to some more "classic" character. Bummer, I was so pleased with an actual up-arrow. 

What does "echo $LANG" tell you?

**Comment by karinlag** [comment]
(alv) [karinlag@abel ~]$ echo $LANG
en_US.iso885915
(alv) [karinlag@abel ~]$

And, even after reinstall I still get the same error.

However, I tried on a different computer with en_GB.UTF-8, and then no error.

karin

**Comment by arvestad** [comment]
OK, thanks, I need to get my hands on some different systems to try this out on.
