### ISSUE TITLE
Custom colouring

### ISSUE THREAD

**Issue by jrjhealey** [arvestad/alv#7]
Hi @arvestad 

Would it be an option to offer further colour customisation (perhaps as a config file, or more predefined scheme options?).

For those of us that run the more 'exotic' terminal colours, some of the default alignment schemes don't render quite so nicely, so if there's a method to specify colours that would be really useful (no rush!).

Cheers!

Joe

**Comment by arvestad** [comment]
Hi!

Yes, I am interested in providing color customization. My thought has been to primarily offer a couple of color schemes, rather than full customization, mostly because the color support for a console-based tool is very limited.

I am not strong at graphics and color choices, so do let me know if you have suggestions. 

I recently got a patch from a friend who works with a black background (which apparently was a case alv was not doing well on). It simply ensures that the characters always have a color that works with the implemented color schemes. Since it might help you, I decided to push a release to pypi.org with that change: v1.3.2. Could you let me know if it was helpful? It will be a while before I implement a more general color system, but I don’t mind providing small fixes. 

	Cheers,
	Lars

**Comment by jrjhealey** [comment]
I work mostly on a dark blue (so assume black perhaps) background and I notice a similar thing. I know dark/solarized colour schemes are very popular in general so it would be good to support those more directly. When I'm back at that specific computer I'll perhaps upload a screen shot by way of example.

Off the top of my head I cant think of a specific colour palette, but[ this site ](http://tools.medialab.sciences-po.fr/iwanthue/) has many useful palettes so approximating those through xterm colours or similar might be a good place to start.

I'll give the pypi release a try on the darker background and report back :)

**Comment by arvestad** [comment]
I am quite sure you had the same problem as my friend. 

That's an interesting site you link to. I don't think it helps me though, because there are only 8 colors in two intensities available. I use the colorama module and you can see the colors [here](https://pypi.org/project/colorama/). If I had full palette control, I would have picked [colors from a Wes Anderson movie](http://www.anothermag.com/art-photography/3586/wes-andersons-colour-palettes). :-)

Please report on the v1.3.2 release. :-)

**Comment by ampodu** [comment]
Hi,
I am using a darker theme in my terminal and I just updated alv and the colors are a lot better now. Thanks :)

Regarding the custom color scheme I have an additional request, it would be great if you could give an option to color the letters based on conservation.

Thank you for this great program!

**Comment by arvestad** [comment]
Thanks ampodu! 

How would such a conservation color look like? The color choices are quite limited for console-based programs. But I am very open for suggestions.

And have you tried the --majority option? It was designed to help indicate conservation.

**Comment by ampodu** [comment]
I tried --majority and it I nearly did not realize that it was actually doing something since the background color of those columns don't really stand out. I would prefer it if those columns had the normal terminal background and text color.

However, the majority option is not really what I am looking for. I am working with very similar sequences that have point mutations. I think proper conservation coloring is not possible, but it would be nice if the all the bases that differ from the majority were colored. 

If you are looking for more to add: A final row with blocks indicating the conservation and the majority AA or base below that.

**Comment by arvestad** [comment]
Thanks for suggestions! I will try to look at this later this winter.

**Comment by jrjhealey** [comment]
Finally got around to testing `1.3.2`. I can confirm the colours look much better already!

Custom colouring would be nice in future if you ever figure out how best to go about it.
